// src/app.vue
<script lang="ts">
import Vue from "vue";
import finishWorkSound from "./assets/work-finish.mp3";
import finishBreakSound from "./assets/break-finish.mp3";

type Seconds = number

enum TimerState {
  Idle = "IDLE",
  Ticking = "TICKING",
  Paused = "PAUSED",
  Finished = "FINISHED"
}

type Timer = {
  value: Seconds;
  state: TimerState;
}

enum CycleName {
  Work = "WORK",
  Break = "BREAK",
  LongBreak = "LONG_BREAK"
}

type Cycle = {
  name: CycleName;
  time: Seconds;
}

type Data = {
  timer: Timer;
  cycle: Cycle;
  setIntervalId: number;
  sessionCount: number;

  sound: {
    work: HTMLAudioElement;
    break: HTMLAudioElement;
  }

  TimerState: typeof TimerState;
}

export default Vue.extend({
  name: "App",

  data(): Data {
    return {
      timer: { value: 4, state: TimerState.Idle },
      cycle: { name: CycleName.Work, time: 4 },
      setIntervalId: -1,
      sessionCount: 0,

      sound: {
        work: new Audio(finishWorkSound),
        break: new Audio(finishBreakSound)
      },

      TimerState
    };
  },

  computed: {
    formattedTimer(): string {
      const min = Math.floor(this.timer.value / 60);
      const sec = this.timer.value % 60;

      return [min, sec].map(v => String(v).padStart(2, "0")).join(":");
    }
  },

  destroyed() {
    this.resetInterval();
    this.sound.work.pause();
    this.sound.break.pause();
  },

  methods: {
    resetInterval() {
      if (this.setIntervalId !== -1) {
        clearInterval(this.setIntervalId);
        this.setIntervalId = -1;
      }
    },

    startTimer() {
      console.log("Timer Started");
      if (this.cycle.name === CycleName.Work &&
          this.timer.state === TimerState.Idle) {
        this.sessionCount += 1;
      }

      this.timer.state = TimerState.Ticking;

      this.setIntervalId = setInterval(() => {
        if (this.timer.value > 0) {
          this.timer.value -= 1;
        } else {
          this.finishTimer();
        }
      }, 1000);
    },

    pauseTimer() {
      this.timer.state = TimerState.Paused;
      this.resetInterval();
    },

    finishTimer() {
      this.timer.state = TimerState.Finished;
      this.resetInterval();

      if (this.cycle.name === CycleName.Work) {
        this.sound.work.play();
      } else {
        this.sound.break.play();
      }
    },

    nextTimer() {
      this.timer.state = TimerState.Idle;

      if (this.cycle.name === CycleName.Break ||
          this.cycle.name === CycleName.LongBreak) {
        if (this.cycle.name === CycleName.LongBreak) {
          this.sessionCount = 0;
        }
        this.cycle = { name: CycleName.Work, time: 4 };
        this.timer.value = 4;
      } else if (this.sessionCount >= 3) {
        this.cycle = { name: CycleName.LongBreak, time: 2 };
        this.timer.value = 2;
      } else {
        this.cycle = { name: CycleName.Break, time: 1 };
        this.timer.value = 1;
      }
    }
  }
});
</script>

<template lang="pug">
  div
    h1 Pomodoro
    br

    h1 Timer: {{ formattedTimer }}
    br

    p Cycle Name: {{ cycle.name }}
    br

    p Session: {{ sessionCount }} / 3
    br

    button(
      v-if="timer.state === TimerState.Idle || timer.state === TimerState.Paused"
      @click="startTimer"
    ) Start

    button(
      v-else-if="timer.state === TimerState.Ticking"
      @click="pauseTimer"
    ) Pause

    button(v-else @click="nextTimer") Next
</template>

<style scoped lang="scss">
</style>

// src/app.tsx
import React from "react";
import { usePomodoro, TimerState, Cycle } from "./pomodoro";
import type { Seconds } from "./pomodoro";

import workFinishSound from "./assets/work-finish.mp3";
import breakFinishSound from "./assets/break-finish.mp3";

function App() {
  const pomodoro = usePomodoro();

  const sound = React.useRef<HTMLAudioElement>(new Audio());
  const interval = React.useRef<number>(-1);
  const intervalCallback = React.useRef<() => void>(intervalCb);

  React.useEffect(() => {
    intervalCallback.current = intervalCb;
  });

  React.useEffect(() => {
    const s = sound.current;

    return () => {
      resetInterval();
      s.pause();
    }
  }, []);

  function intervalCb() {
    const isFinished = pomodoro.tick();
    if (isFinished) finishTimer();
  }

  function resetInterval() {
    if (interval.current !== -1) {
      clearInterval(interval.current);
      interval.current = -1;
    }
  }

  function startTimer() {
    pomodoro.start();

    interval.current = window.setInterval(() => {
      intervalCallback.current();
    }, 1000);
  }

  function finishTimer() {
    pomodoro.finish();
    resetInterval();

    if (pomodoro.cycle === Cycle.Work) {
      sound.current.src = workFinishSound;
    } else {
      sound.current.src = breakFinishSound;
    }

    sound.current.play();
  }

  function pauseTimer() {
    pomodoro.pause();
    resetInterval();
  }

  function nextTimer() {
    pomodoro.next();
  }

  return (
    <div>
      <h1>Pomodoro</h1>
      <h2>{printCycle(pomodoro.cycle)}</h2>

      <Timer time={pomodoro.timer} />

      <TimerControls
        onStart={startTimer}
        onPause={pauseTimer}
        onNext={nextTimer}
        state={pomodoro.timerState}
      />

      <p>Session: {pomodoro.sessionCount}/3</p>
    </div>
  );
}

type TimerProps = { time: Seconds }

function Timer({ time }: TimerProps) {
  return(
    <p>{printTimer(time)}</p>
  );
}

type TimerControlsProps = {
  onStart: () => void;
  onPause: () => void;
  onNext: () => void;
  state: TimerState; 
}

function TimerControls(props: TimerControlsProps) {
  if (props.state === TimerState.Idle || props.state === TimerState.Paused) {
    return(
      <button onClick={props.onStart}>
        Start
      </button>
    );
  }

  if (props.state === TimerState.Ticking) {
    return(
      <button onClick={props.onPause}>
        Pause
      </button>
    );
  }

  return(
    <button onClick={props.onNext}>
      Next
    </button>
  );
}

function printTimer(value: Seconds): string {
  const min = Math.floor(value / 60);
  const sec = value % 60;

  return [min, sec].map(v => String(v).padStart(2, "0")).join(":");
}

function printCycle(cycle: Cycle) {
  const names = {
    [Cycle.Work]: "Work",
    [Cycle.Break]: "Break",
    [Cycle.LongBreak]: "Long Break"
  };

  return names[cycle];
}

export default App;
